# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.title_number import TitleNumber  # noqa: F401,E501
from swagger_server import util


class ApplicationRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title_number: TitleNumber=None):  # noqa: E501
        """ApplicationRequest - a model defined in Swagger

        :param title_number: The title_number of this ApplicationRequest.  # noqa: E501
        :type title_number: TitleNumber
        """
        self.swagger_types = {
            'title_number': TitleNumber
        }

        self.attribute_map = {
            'title_number': 'title_number'
        }
        self._title_number = title_number

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplicationRequest of this ApplicationRequest.  # noqa: E501
        :rtype: ApplicationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title_number(self) -> TitleNumber:
        """Gets the title_number of this ApplicationRequest.


        :return: The title_number of this ApplicationRequest.
        :rtype: TitleNumber
        """
        return self._title_number

    @title_number.setter
    def title_number(self, title_number: TitleNumber):
        """Sets the title_number of this ApplicationRequest.


        :param title_number: The title_number of this ApplicationRequest.
        :type title_number: TitleNumber
        """
        if title_number is None:
            raise ValueError("Invalid value for `title_number`, must not be `None`")  # noqa: E501

        self._title_number = title_number
