# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Proprietor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, proprietor_type: str=None):  # noqa: E501
        """Proprietor - a model defined in Swagger

        :param proprietor_type: The proprietor_type of this Proprietor.  # noqa: E501
        :type proprietor_type: str
        """
        self.swagger_types = {
            'proprietor_type': str
        }

        self.attribute_map = {
            'proprietor_type': 'proprietor_type'
        }
        self._proprietor_type = proprietor_type

    @classmethod
    def from_dict(cls, dikt) -> 'Proprietor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Proprietor of this Proprietor.  # noqa: E501
        :rtype: Proprietor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def proprietor_type(self) -> str:
        """Gets the proprietor_type of this Proprietor.


        :return: The proprietor_type of this Proprietor.
        :rtype: str
        """
        return self._proprietor_type

    @proprietor_type.setter
    def proprietor_type(self, proprietor_type: str):
        """Sets the proprietor_type of this Proprietor.


        :param proprietor_type: The proprietor_type of this Proprietor.
        :type proprietor_type: str
        """

        self._proprietor_type = proprietor_type
