# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ScheduleCode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    D = "d"
    F = "f"
    H = "h"
    L = "l"
    M = "m"
    P = "p"
    Q = "q"
    R = "r"
    S = "s"
    T = "t"
    W = "w"
    X = "x"
    Y = "y"
    Z = "z"
    def __init__(self):  # noqa: E501
        """ScheduleCode - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ScheduleCode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScheduleCode of this ScheduleCode.  # noqa: E501
        :rtype: ScheduleCode
        """
        return util.deserialize_model(dikt, cls)
