# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.application_reference import ApplicationReference  # noqa: F401,E501
from swagger_server.models.application_request_response import ApplicationRequestResponse  # noqa: F401,E501
from swagger_server.models.title import Title  # noqa: F401,E501
from swagger_server.models.validation_success_response import ValidationSuccessResponse  # noqa: F401,E501
from swagger_server import util


class SubmitApplicationResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, title: Title=None, applications: List[ApplicationRequestResponse]=None, application_reference: ApplicationReference=None):  # noqa: E501
        """SubmitApplicationResponse - a model defined in Swagger

        :param status: The status of this SubmitApplicationResponse.  # noqa: E501
        :type status: int
        :param title: The title of this SubmitApplicationResponse.  # noqa: E501
        :type title: Title
        :param applications: The applications of this SubmitApplicationResponse.  # noqa: E501
        :type applications: List[ApplicationRequestResponse]
        :param application_reference: The application_reference of this SubmitApplicationResponse.  # noqa: E501
        :type application_reference: ApplicationReference
        """
        self.swagger_types = {
            'status': int,
            'title': Title,
            'applications': List[ApplicationRequestResponse],
            'application_reference': ApplicationReference
        }

        self.attribute_map = {
            'status': 'status',
            'title': 'title',
            'applications': 'applications',
            'application_reference': 'application_reference'
        }
        self._status = status
        self._title = title
        self._applications = applications
        self._application_reference = application_reference

    @classmethod
    def from_dict(cls, dikt) -> 'SubmitApplicationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubmitApplicationResponse of this SubmitApplicationResponse.  # noqa: E501
        :rtype: SubmitApplicationResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this SubmitApplicationResponse.

        The HTTP status code returned by the server with this response.  # noqa: E501

        :return: The status of this SubmitApplicationResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this SubmitApplicationResponse.

        The HTTP status code returned by the server with this response.  # noqa: E501

        :param status: The status of this SubmitApplicationResponse.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def title(self) -> Title:
        """Gets the title of this SubmitApplicationResponse.


        :return: The title of this SubmitApplicationResponse.
        :rtype: Title
        """
        return self._title

    @title.setter
    def title(self, title: Title):
        """Sets the title of this SubmitApplicationResponse.


        :param title: The title of this SubmitApplicationResponse.
        :type title: Title
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def applications(self) -> List[ApplicationRequestResponse]:
        """Gets the applications of this SubmitApplicationResponse.


        :return: The applications of this SubmitApplicationResponse.
        :rtype: List[ApplicationRequestResponse]
        """
        return self._applications

    @applications.setter
    def applications(self, applications: List[ApplicationRequestResponse]):
        """Sets the applications of this SubmitApplicationResponse.


        :param applications: The applications of this SubmitApplicationResponse.
        :type applications: List[ApplicationRequestResponse]
        """

        self._applications = applications

    @property
    def application_reference(self) -> ApplicationReference:
        """Gets the application_reference of this SubmitApplicationResponse.


        :return: The application_reference of this SubmitApplicationResponse.
        :rtype: ApplicationReference
        """
        return self._application_reference

    @application_reference.setter
    def application_reference(self, application_reference: ApplicationReference):
        """Sets the application_reference of this SubmitApplicationResponse.


        :param application_reference: The application_reference of this SubmitApplicationResponse.
        :type application_reference: ApplicationReference
        """
        if application_reference is None:
            raise ValueError("Invalid value for `application_reference`, must not be `None`")  # noqa: E501

        self._application_reference = application_reference
