# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.title_status import TitleStatus  # noqa: F401,E501
from swagger_server import util


class TitleStatusInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, value: TitleStatus=None, _date: date=None):  # noqa: E501
        """TitleStatusInfo - a model defined in Swagger

        :param value: The value of this TitleStatusInfo.  # noqa: E501
        :type value: TitleStatus
        :param _date: The _date of this TitleStatusInfo.  # noqa: E501
        :type _date: date
        """
        self.swagger_types = {
            'value': TitleStatus,
            '_date': date
        }

        self.attribute_map = {
            'value': 'value',
            '_date': 'date'
        }
        self._value = value
        self.__date = _date

    @classmethod
    def from_dict(cls, dikt) -> 'TitleStatusInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TitleStatusInfo of this TitleStatusInfo.  # noqa: E501
        :rtype: TitleStatusInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> TitleStatus:
        """Gets the value of this TitleStatusInfo.


        :return: The value of this TitleStatusInfo.
        :rtype: TitleStatus
        """
        return self._value

    @value.setter
    def value(self, value: TitleStatus):
        """Sets the value of this TitleStatusInfo.


        :param value: The value of this TitleStatusInfo.
        :type value: TitleStatus
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def _date(self) -> date:
        """Gets the _date of this TitleStatusInfo.

        The date that the status of the title was changed.   # noqa: E501

        :return: The _date of this TitleStatusInfo.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this TitleStatusInfo.

        The date that the status of the title was changed.   # noqa: E501

        :param _date: The _date of this TitleStatusInfo.
        :type _date: date
        """

        self.__date = _date
