# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TitleStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    OPEN = "open"
    CLOSED = "closed"
    def __init__(self):  # noqa: E501
        """TitleStatus - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TitleStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TitleStatus of this TitleStatus.  # noqa: E501
        :rtype: TitleStatus
        """
        return util.deserialize_model(dikt, cls)
