# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.application_request_response import ApplicationRequestResponse  # noqa: F401,E501
from swagger_server.models.title import Title  # noqa: F401,E501
from swagger_server import util


class ValidationSuccessResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, title: Title=None, applications: List[ApplicationRequestResponse]=None):  # noqa: E501
        """ValidationSuccessResponse - a model defined in Swagger

        :param status: The status of this ValidationSuccessResponse.  # noqa: E501
        :type status: int
        :param title: The title of this ValidationSuccessResponse.  # noqa: E501
        :type title: Title
        :param applications: The applications of this ValidationSuccessResponse.  # noqa: E501
        :type applications: List[ApplicationRequestResponse]
        """
        self.swagger_types = {
            'status': int,
            'title': Title,
            'applications': List[ApplicationRequestResponse]
        }

        self.attribute_map = {
            'status': 'status',
            'title': 'title',
            'applications': 'applications'
        }
        self._status = status
        self._title = title
        self._applications = applications

    @classmethod
    def from_dict(cls, dikt) -> 'ValidationSuccessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValidationSuccessResponse of this ValidationSuccessResponse.  # noqa: E501
        :rtype: ValidationSuccessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this ValidationSuccessResponse.

        The HTTP status code returned by the server with this response.  # noqa: E501

        :return: The status of this ValidationSuccessResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this ValidationSuccessResponse.

        The HTTP status code returned by the server with this response.  # noqa: E501

        :param status: The status of this ValidationSuccessResponse.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def title(self) -> Title:
        """Gets the title of this ValidationSuccessResponse.


        :return: The title of this ValidationSuccessResponse.
        :rtype: Title
        """
        return self._title

    @title.setter
    def title(self, title: Title):
        """Sets the title of this ValidationSuccessResponse.


        :param title: The title of this ValidationSuccessResponse.
        :type title: Title
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def applications(self) -> List[ApplicationRequestResponse]:
        """Gets the applications of this ValidationSuccessResponse.


        :return: The applications of this ValidationSuccessResponse.
        :rtype: List[ApplicationRequestResponse]
        """
        return self._applications

    @applications.setter
    def applications(self, applications: List[ApplicationRequestResponse]):
        """Sets the applications of this ValidationSuccessResponse.


        :param applications: The applications of this ValidationSuccessResponse.
        :type applications: List[ApplicationRequestResponse]
        """

        self._applications = applications
