# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
#from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server.models.one_of_validation_success_value import OneOfValidationSuccessValue
from swagger_server import util


class ValidationSuccess(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, property_name: str=None, value: OneOfValidationSuccessValue=None):  # noqa: E501
        """ValidationSuccess - a model defined in Swagger

        :param property_name: The property_name of this ValidationSuccess.  # noqa: E501
        :type property_name: str
        :param value: The value of this ValidationSuccess.  # noqa: E501
        :type value: OneOfValidationSuccessValue
        """
        self.swagger_types = {
            'property_name': str,
            'value': OneOfValidationSuccessValue
        }

        self.attribute_map = {
            'property_name': 'property_name',
            'value': 'value'
        }
        self._property_name = property_name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'ValidationSuccess':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValidationSuccess of this ValidationSuccess.  # noqa: E501
        :rtype: ValidationSuccess
        """
        return util.deserialize_model(dikt, cls)

    @property
    def property_name(self) -> str:
        """Gets the property_name of this ValidationSuccess.

        The name of the property that passed validation.  # noqa: E501

        :return: The property_name of this ValidationSuccess.
        :rtype: str
        """
        return self._property_name

    @property_name.setter
    def property_name(self, property_name: str):
        """Sets the property_name of this ValidationSuccess.

        The name of the property that passed validation.  # noqa: E501

        :param property_name: The property_name of this ValidationSuccess.
        :type property_name: str
        """
        if property_name is None:
            raise ValueError("Invalid value for `property_name`, must not be `None`")  # noqa: E501

        self._property_name = property_name

    @property
    def value(self) -> OneOfValidationSuccessValue:
        """Gets the value of this ValidationSuccess.

        The value of the property that passed validation.  # noqa: E501

        :return: The value of this ValidationSuccess.
        :rtype: OneOfValidationSuccessValue
        """
        return self._value

    @value.setter
    def value(self, value: OneOfValidationSuccessValue):
        """Sets the value of this ValidationSuccess.

        The value of the property that passed validation.  # noqa: E501

        :param value: The value of this ValidationSuccess.
        :type value: OneOfValidationSuccessValue
        """

        self._value = value
