# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.application_request_response import ApplicationRequestResponse  # noqa: F401,E501
from swagger_server.models.title import Title  # noqa: F401,E501
from swagger_server import util


class ValidationErrorResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, error_message: str=None, title: Title=None, applications: List[ApplicationRequestResponse]=None):  # noqa: E501
        """ValidationErrorResponse - a model defined in Swagger

        :param status: The status of this ValidationErrorResponse.  # noqa: E501
        :type status: int
        :param error_message: The error_message of this ValidationErrorResponse.  # noqa: E501
        :type error_message: str
        :param title: The title of this ValidationErrorResponse.  # noqa: E501
        :type title: Title
        :param applications: The applications of this ValidationErrorResponse.  # noqa: E501
        :type applications: List[ApplicationRequestResponse]
        """
        self.swagger_types = {
            'status': int,
            'error_message': str,
            'title': Title,
            'applications': List[ApplicationRequestResponse]
        }

        self.attribute_map = {
            'status': 'status',
            'error_message': 'error_message',
            'title': 'title',
            'applications': 'applications'
        }
        self._status = status
        self._error_message = error_message
        self._title = title
        self._applications = applications

    @classmethod
    def from_dict(cls, dikt) -> 'ValidationErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValidationErrorResponse of this ValidationErrorResponse.  # noqa: E501
        :rtype: ValidationErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this ValidationErrorResponse.

        The HTTP status code returned by the server with this response.  # noqa: E501

        :return: The status of this ValidationErrorResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this ValidationErrorResponse.

        The HTTP status code returned by the server with this response.  # noqa: E501

        :param status: The status of this ValidationErrorResponse.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error_message(self) -> str:
        """Gets the error_message of this ValidationErrorResponse.

        A human-readable message that provides a summary of the cause of the error.  # noqa: E501

        :return: The error_message of this ValidationErrorResponse.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this ValidationErrorResponse.

        A human-readable message that provides a summary of the cause of the error.  # noqa: E501

        :param error_message: The error_message of this ValidationErrorResponse.
        :type error_message: str
        """
        if error_message is None:
            raise ValueError("Invalid value for `error_message`, must not be `None`")  # noqa: E501

        self._error_message = error_message

    @property
    def title(self) -> Title:
        """Gets the title of this ValidationErrorResponse.


        :return: The title of this ValidationErrorResponse.
        :rtype: Title
        """
        return self._title

    @title.setter
    def title(self, title: Title):
        """Sets the title of this ValidationErrorResponse.


        :param title: The title of this ValidationErrorResponse.
        :type title: Title
        """

        self._title = title

    @property
    def applications(self) -> List[ApplicationRequestResponse]:
        """Gets the applications of this ValidationErrorResponse.


        :return: The applications of this ValidationErrorResponse.
        :rtype: List[ApplicationRequestResponse]
        """
        return self._applications

    @applications.setter
    def applications(self, applications: List[ApplicationRequestResponse]):
        """Sets the applications of this ValidationErrorResponse.


        :param applications: The applications of this ValidationErrorResponse.
        :type applications: List[ApplicationRequestResponse]
        """

        self._applications = applications
